"""init schema

Revision ID: 906c31ab74fe
Revises: 
Create Date: 2026-09-06 21:13:21.197815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '906c31ab74fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practice_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('duration_limit_sec', sa.Integer(), nullable=True),
    sa.Column('elapsed_sec', sa.Integer(), nullable=False),
    sa.Column('question_ids', sa.JSON(), nullable=False),
    sa.Column('filter_snapshot', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_session_code'), ['code'], unique=True)

    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.SmallInteger(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('answer', sa.JSON(), nullable=False),
    sa.Column('judge_config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_question_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_type'), ['type'], unique=False)

    op.create_table('mistake',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('first_wrong_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_wrong_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('cleared_count', sa.Integer(), nullable=False),
    sa.Column('mastered', sa.Boolean(), nullable=False),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mistake', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mistake_question_id'), ['question_id'], unique=True)

    op.create_table('question_stat',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('last_result', sa.SmallInteger(), nullable=True),
    sa.Column('mastery', sa.SmallInteger(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('question_tag',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'tag_id')
    )
    op.create_table('session_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('score_weight', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('answered', sa.Boolean(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('spent_sec', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['practice_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_id', name='uq_item_session_question'),
    sa.UniqueConstraint('session_id', 'seq', name='uq_item_session_seq')
    )
    op.create_table('attempt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('judge_detail', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['session_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['practice_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempt_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempt_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempt_session_id'))
        batch_op.drop_index(batch_op.f('ix_attempt_question_id'))

    op.drop_table('attempt')
    op.drop_table('session_item')
    op.drop_table('question_tag')
    op.drop_table('question_stat')
    with op.batch_alter_table('mistake', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mistake_question_id'))

    op.drop_table('mistake')
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_type'))
        batch_op.drop_index(batch_op.f('ix_question_status'))
        batch_op.drop_index(batch_op.f('ix_question_difficulty'))
        batch_op.drop_index(batch_op.f('ix_question_code'))
        batch_op.drop_index(batch_op.f('ix_question_category_id'))

    op.drop_table('question')
    op.drop_table('tag')
    with op.batch_alter_table('practice_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_session_code'))

    op.drop_table('practice_session')
    op.drop_table('category')
    # ### end Alembic commands ###
